//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampePro.OracleClientExample {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OracleClientExample.ILinkOracle")]
    public interface ILinkOracle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkOracle/QueryAllCREW", ReplyAction="http://tempuri.org/ILinkOracle/QueryAllCREWResponse")]
        System.Data.DataSet QueryAllCREW();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILinkOracle/QueryAllCREW", ReplyAction="http://tempuri.org/ILinkOracle/QueryAllCREWResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> QueryAllCREWAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILinkOracleChannel : ExampePro.OracleClientExample.ILinkOracle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkOracleClient : System.ServiceModel.ClientBase<ExampePro.OracleClientExample.ILinkOracle>, ExampePro.OracleClientExample.ILinkOracle {
        
        public LinkOracleClient() {
        }
        
        public LinkOracleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinkOracleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkOracleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkOracleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet QueryAllCREW() {
            return base.Channel.QueryAllCREW();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> QueryAllCREWAsync() {
            return base.Channel.QueryAllCREWAsync();
        }
    }
}
